# Generated by Django 3.2.1 on 2022-07-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0006_auto_20220722_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag']},
        ),
    ]
